version: 0.2

env:
  secrets-manager:
    RHEL_USERNAME: "nodeadm-e2e-tests-redhat-credentials:username"
    RHEL_PASSWORD: "nodeadm-e2e-tests-redhat-credentials:password"

phases:
  build:
    commands:
    - CLUSTER_NAME_PREFIX="${KUBERNETES_VERSION}-${CNI}-"
    - CLUSTER_NAME="${CLUSTER_NAME_PREFIX}$(echo $CODEBUILD_BUILD_ID | tr ':' '-')"
    - ARCH="$([ "x86_64" = "$(uname -m)" ] && echo amd64 || echo arm64)"
    - ./_bin/$ARCH/e2e-test cleanup -p $CLUSTER_NAME_PREFIX
    - ./hack/run-e2e.sh $CLUSTER_NAME $AWS_REGION $KUBERNETES_VERSION $CNI s3://$ARTIFACTS_BUCKET/latest-pre/linux/amd64/nodeadm s3://$ARTIFACTS_BUCKET/latest-pre/linux/arm64/nodeadm $LOGS_BUCKET e2e-artifacts $ENDPOINT

reports:
  e2e-reports:
    files:
      - e2e-reports/junit-nodeadm.xml
    file-format: "JUNITXML"

artifacts:
  files:
  - "e2e-artifacts/*"
